### ISSUE TITLE
Enable Near Mode for K4W

### ISSUE THREAD

**Issue by dxli** [OpenKinect/libfreenect#274]
Hi,

I need to set my kinect for windows(K4W) in near mode.

with microsoft kinect SDK, it's done by the following line,

m_pNuiSensor->NuiImageStreamSetImageFrameFlags(m_pDepthStreamHandle, NUI_IMAGE_STREAM_FLAG_ENABLE_NEAR_MODE );

Any help is appreciated on how to get the similar done in libfreenect.

Thanks,

dxli

**Comment by piedar** [comment]
Assumed fixed.  File a new issue if it's broken.
