### ISSUE TITLE
Add support for Kinect for Xbox 360 Model 1473

### ISSUE THREAD

**Issue by hkzlab** [OpenKinect/libfreenect#316]
Hello,
I write to open an issue on the missing support for this device.
The 1473 model does not work with libfreenect: I always get a "Could not open device" when trying to launch demos using the camera or the tilt motor.

Also, the Xbox NUI Motor doesn't show up when checking with lsusb (testing on Ubuntu 12.10, 32bit):
Bus 001 Device 086: ID 045e:02c2 Microsoft Corp. 
Bus 001 Device 087: ID 045e:02ad Microsoft Corp. Xbox NUI Audio
Bus 001 Device 088: ID 045e:02ae Microsoft Corp. Xbox NUI Camera
If needed, I can provide more verbose lsusb logs.

**Comment by leonardodsan** [comment]
Hello,

I'm trying to use a Kinect device 1473 on a CubieTruck board (OS Linaro 12.04), I got the same problem with the official https://github.com/OpenKinect/libfreenect repository of: "Could not open device". Would you like to know the final solution of this topic to solve the problem?

**Comment by Exomene** [comment]
Sure



*Exomène*
<http://exomene.com/?utm_source=Signature%20Exomene&utm_medium=e-mail&utm_campaign=Signature%20Exomene%20-%3E%20exomene.com>
---
Soundsmith & digital apothecary (http://exomene.com
<http://exomene.com/?utm_source=Signature%20Exomene&utm_medium=e-mail&utm_campaign=Signature%20Exomene%20-%3E%20exomene.com>
)
<http://exomene.com>

2017-04-04 22:07 GMT+02:00 leonardodsan <notifications@github.com>:

**Comment by josuerocha** [comment]
I have the same problem on Ubuntu 16.04 with Kinect v1 1473. Any news upon solving this problem?

**Comment by wizgrav** [comment]
Wow this thread is still alive, that was a good flashback. Without further info from the console I think the first thing to try is checking if permissions are set ok. Try running the app as root. I have recently used the kinect on a raspberry 3 and can confirm that it works ok

**Comment by josuerocha** [comment]
@wizgrav did you use the 1473 version?

**Comment by wizgrav** [comment]
@josuerocha I'm not sure to be honest and can't actually check right now, my kinect is in malta and I'm currently in greece for the holidays. It should work though I setup several gigs with kinects and raspberries on my previous employer and I believe at least one of them would be 1473. Have you tried running as root and it didn't work?

**Comment by josuerocha** [comment]
Yes. I ran it as root and the same errors persist:

' jr@JR-MOBILE:~$ sudo freenect-glview
Kinect camera test
Number of devices found: 1
Found sibling device [same parent]
Failed to set the LED of K4W or 1473 device: -1
Found sibling device [same parent]
Could not open device: -1
Could not open device
'

**Comment by har96** [comment]
Has there been any update on this? I pulled from the master branch and am still getting the same error @josuerocha pasted above. I've already corrected permissions and such.

**Comment by josuerocha** [comment]
@har96 I don't think so. I bought a Kinect 1414 and gave up on 1473 in order to save some project time.

**Comment by har96** [comment]
Mine is actually started working. I uploaded the audio.bin firmware and I'm getting the video stream now.
