### ISSUE TITLE
Request: Option to output incremental frames - useful for tracking

### ISSUE THREAD

**Issue by stevenlovegrove** [OpenKinect/libfreenect#32]
For robotics / visual tracking, the ability to process input with low latency can save computation time and reduce perceptual aliasing, as well as improve closed loop reaction time. In this regard, a rolling shutter (such as that used by the Kinect RGB and IR camera) can offer an advantage.

It would be great if the libfreenect driver additionally offered access to the underlying image frame chunks for sequential processing.

**Comment by piedar** [comment]
Implemented in #351.
