### ISSUE TITLE
Can't run cppview (cpp wrapper broken ?)

### ISSUE THREAD

**Issue by GunMan-fr** [OpenKinect/libfreenect#322]
Hello guys,

I'm having some trouble running cppview.

I did correctly install libfreenect and have no trouble running glview for instance.

But the following error is thrown when I run cppview : 

```
 GL thread
 terminate called after throwing an instance of 'std::runtime_error'
   what():  Cannot process freenect events
 Abandon (core dumped)
```

I tried looking at the previous issues. I found a 2 year old google groups post with a similar problem, but still no solution at the end. It might be related to the GL init process...

Any clue on how to fix this ?

Thanks for your precious help !

**Comment by piedar** [comment]
It means either libusb returned an error or a device disappeared.  It's hard to tell without debug output.
