### ISSUE TITLE
No data on raspberry pi

### ISSUE THREAD

**Issue by xxorde** [OpenKinect/libfreenect#338]
I noticed other people had similar problems, but I did not find an issue. If there is already one, please delete this.

I can compile freenect without any problems.
When I compile a small c program (works fine on other machines)  I don't get any data from  “freenect_sync_get_depth”. Non of the examples works.

The program simply stops and never finishes this function.

In other words, in the following example “done” is never printed.

``` c
short *depth = 0;
uint32_t ts;
FILE *fp;
int ret;

printf("get depth....");
ret = freenect_sync_get_depth((void**)&depth, &ts, 0, FREENECT_DEPTH_MM);
printf(" done\n");
```

How can I find an fix the problem? 
Where to start?

**Comment by AIWintermuteAI** [comment]
It's an old issue, but just in case anybody encounters it, in search of solutions - I recently wrote an article about using Kinect 360 and RTAB-MAP ROS with Rasberry Pi 4, with some tweaks it does work now!
https://www.hackster.io/dmitrywat/rgb-d-slam-with-kinect-on-raspberry-pi-4-ros-melodic-ace795
