### ISSUE TITLE
wrappers/cpp/libfreenect.hpp doesn't compile in C++11 mode

### ISSUE THREAD

**Issue by OsePedro** [OpenKinect/libfreenect#339]
The line `m_devices.insert(std::make_pair<int, FreenectDevice*>(_index, device));` in `wrappers/cpp/libfreenect.hpp`'s `Freenect::createDevice()` function does not compile under the new C++11 definition of `std::make_pair()`, due to its use of rvalue references. In fact, the whole point of `std::make_pair` is to allow you to create `std::pair`s without having to explicitly provide the template parameters. In cases where you want to provide template parameters, you can save 5 characters ("`make_`") by calling the `std::pair` constructor directly.

One solution is to replace the line with `m_devices.insert(std::make_pair(_index, device));`. Alternatively, you could use `m_devices[_index]=device;`. Both solutions are compatible with earlier versions of C++.

**Comment by maxrafiandy** [comment]
Thanks. you save my day.
