### ISSUE TITLE
Undefined reference to libfreenect

### ISSUE THREAD

**Issue by game4cesc** [OpenKinect/libfreenect#344]
I'm trying to compute a metrics 3D reconstruction in Kinect using the instruction specified in www6.in.tum.de/Main/ResearchKinect3d 

I was able to install the suitable libfreenect version accordingly and set the paths to my Makefile of freenect as it is supposed to. The problem is when I try to run make from Freenect, it returns the following make error msg ...

./FreeKinect3d: 1: ./FreeKinect3d: Syntax error: word unexpected (expecting ")")

FreeKinect3d.cpp:(.text+0x31): undefined reference to `freenect_set_led'
FreeKinect3d.cpp:(.text+0x44): undefined reference to `freenect_set_depth_callback'
FreeKinect3d.cpp:(.text+0x57): undefined reference to `freenect_set_video_callback'
FreeKinect3d.cpp:(.text+0x6a): undefined reference to `freenect_set_video_format'
FreeKinect3d.cpp:(.text+0x7d): undefined reference to `freenect_set_depth_format'
FreeKinect3d.cpp:(.text+0x88): undefined reference to `freenect_start_depth'
FreeKinect3d.cpp:(.text+0x93): undefined reference to `freenect_start_video'
FreeKinect3d.cpp:(.text+0xc7): undefined reference to `freenect_stop_depth'
FreeKinect3d.cpp:(.text+0xd2): undefined reference to `freenect_stop_video'
FreeKinect3d.cpp:(.text+0xdd): undefined reference to `freenect_close_device'
FreeKinect3d.cpp:(.text+0xe8): undefined reference to `freenect_shutdown'
FreeKinect3d.cpp:(.text+0x107): undefined reference to `freenect_process_events'
./lib/libFreeKinect3d.a(FreeKinect3d.o): In function `FreeKinect3d::init()':
FreeKinect3d.cpp:(.text+0x197): undefined reference to `freenect_init'
FreeKinect3d.cpp:(.text+0x1b2): undefined reference to `freenect_set_log_level'
FreeKinect3d.cpp:(.text+0x1bd): undefined reference to `freenect_num_devices'
FreeKinect3d.cpp:(.text+0x1df): undefined reference to `freenect_open_device'
./lib/libFreeKinect3d.a(FK3dViewer.o): In function `FK3dViewer::specialFunc(int, int, int)':
FK3dViewer.cpp:(.text+0x10dd): undefined reference to `freenect_set_tilt_degs'
collect2: error: ld returned 1 exit status
make: *** [all] Error 1

==========
My machine Ubuntu 12.10, 32-bit and Kinect for Microsoft
==========

If anyone have any idea to solve this issue, I'd very much appreciate it. Thanks in advance.

Cheers,
Eskender Tamrat

**Comment by piedar** [comment]
If you use CMake you can write

    find_package(libfreenect REQUIRED)
    include_directories(${FREENECT_INCLUDE_DIRS})
    add_executable(my-program my-program.c)
    target_link_libraries(my-program ${FREENECT_LIBRARIES})

Otherwise, you need to add linker flags to your Makefile so that the compiler is called like so:

    gcc -o my-program my-program.c -L/usr/lib -lfreenect

Or using pkg-config:

    gcc -o my-program my-program.c `pkg-config --libs libfreenect`
