### ISSUE TITLE
Auto exposure (gain), auto white balance switching does not work in freenect-glview example

### ISSUE THREAD

**Issue by alexander-hagg** [OpenKinect/libfreenect#386]
In v0.2.0 you added control of auto exposure and white balance, as mentioned in #332. I am running the current main branch. After starting the freenect-glview example and then consecutively pushing 'e', 'b', 'e, 'b', I get the following output, but no change in device behaviour. I flip my lights on and off, but autoexposure still seems to be on.

```
'w' - tilt up, 's' - level, 'x' - tilt down, '0'-'6' - select LED mode 
'f' - change video format, 'm' - mirror video, 'o' - rotate video with accelerometer 
'e' - auto exposure, 'b' - white balance, 'r' - raw color 
read_cmos_register: 0x0106 =>
write_cmos_register: 0x0106 <= 0x7fff 
read_cmos_register: 0x0106 =>
write_cmos_register: 0x0106 <= 0x02
read_cmos_register: 0x0106 =>
write_cmos_register: 0x0106 <= 0x00
read_cmos_register: 0x0106 =>
write_cmos_register: 0x0106 <= 0x00
read_cmos_register: 0x0106 =>
write_cmos_register: 0x0106 <= 0x4000
read_cmos_register: 0x0106 =>
write_cmos_register: 0x0106 <= 0x02
```

**Comment by usama-ghufran** [comment]
Hey, has this issue been resolved? Can we control the exposure, colour correction and white balance of the kinect with the latest release?

**Comment by Masterxilo** [comment]
I think exposure, white-balance and colour correction can only be controlled with "Kinect for Windows" devices, not with vanilla XBox 360 devices.

**Comment by piedar** [comment]
Done via #670
