### ISSUE TITLE
Libfreenect OSX 10.9 MacBookPro doesn't work

### ISSUE THREAD

**Issue by mecwerks** [OpenKinect/libfreenect#394]
I'm not sure if this is strictly to libfreenect as NI Mate failed to work as well. But when trying to use freenect-glview i get lots of this

```
[Stream 80] Lost 1 total packets in 0 frames (inf lppf)
[Stream 80] Lost 4 total packets in 0 frames (inf lppf)
[Stream 80] Lost 6 total packets in 0 frames (inf lppf)
[Stream 80] Lost 9 total packets in 0 frames (inf lppf)
[Stream 80] Lost 14 total packets in 0 frames (inf lppf)
[Stream 80] Lost 17 total packets in 0 frames (inf lppf)
[Stream 80] Lost 19 total packets in 0 frames (inf lppf)
[Stream 80] Lost 20 total packets in 0 frames (inf lppf)
Isochronous transfer error: 6
[Stream 80] Lost 21 total packets in 0 frames (inf lppf)
Isochronous transfer error: 6
```

And only rarely get anything to show.
![screen shot 2014-06-02 at 12 00 41 am](https://cloud.githubusercontent.com/assets/589030/3143804/ebce8f72-ea0a-11e3-8499-4a8ee37001e8.png)

**Comment by micuat** [comment]
@piedar I'm having exactly the same issue with OSX 10.9.5. I tried both the master branch and v0.4.1 but neither works. I also tried building with audio and changing XFER parameters, but the output is the same.

I don't understand but openFrameworks (0.8.4 release)'s libfreenect works fine with the same environment.

**Comment by SiggyF** [comment]
I got this error due to an old version of libusb found by cmake. Once I manually told cmake where to find libusb 1.0.21 it was solved for me.
