### ISSUE TITLE
One minute tracking using libFreenectDriver

### ISSUE THREAD

**Issue by paco10121968** [OpenKinect/libfreenect#402]
hi all,
i have some problems using libFreenect as OpenNI Driver on macbook pro retina late 2013 osx 10.9.4

i didnt compiled using BUILD_AUDIO support

i am using NITE2 v2.2, OpenNI v2.2.0.33, libusb 1.0.18
i am using libFreenectDriver v0.4.3 or v0.4.1
i am using the K4W model n. 1517
using NITE user tracking, after one minute the NITE middleware stop to tracking the user and calibrate again.

Any Suggestion? i have this log on starting  freenect-glview:
Number of devices found: 1
GL thread
write_register: 0x0105 <= 0x00
write_register: 0x0006 <= 0x00
write_register: 0x0012 <= 0x03
write_register: 0x0013 <= 0x01
write_register: 0x0014 <= 0x1e
write_register: 0x0006 <= 0x02
write_register: 0x0017 <= 0x00
write_register: 0x000c <= 0x00
write_register: 0x000d <= 0x01
write_register: 0x000e <= 0x1e
[Stream 70] Lost 1 total packets in 0 frames (inf lppf)
[Stream 70] Lost 4 total packets in 0 frames (inf lppf)
write_register: 0x0005 <= 0x01
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Lost 11 packets
[Stream 70] Lost 15 total packets in 6 frames (2.500000 lppf)
[Stream 70] Lost too many packets, resyncing...
write_register: 0x0047 <= 0x00

then several times...

Stream 70] Lost 1978 total packets in 1792 frames (1.103795 lppf)
[Stream 70] Lost too many packets, resyncing...
[Stream 70] Invalid magic b2ff
[Stream 70] Invalid magic b3ff
[Stream 70] Invalid magic b3ff
[Stream 70] Invalid magic b2ff
[Stream 70] Invalid magic b1ff
[Stream 70] Invalid magic b0ff
[Stream 70] Invalid magic b0ff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic b4ff
[Stream 70] Invalid magic b4ff
[Stream 70] Invalid magic b4ff
[Stream 70] Invalid magic b5ff
[Stream 70] Invalid magic b7ff
[Stream 70] Invalid magic b7ff
[Stream 70] Invalid magic b5ff
[Stream 70] Invalid magic b2ff
[Stream 70] Lost 11 packets
[Stream 70] Lost 1989 total packets in 1792 frames (1.109933 lppf)
[Stream 70] Lost too many packets, resyncing...

**Comment by matrivian** [comment]
Hi sllalc, 

Did you find the solution to stop automatic re-calibration of NiTE2? Thank you!

**Comment by silaic** [comment]
yes i find…
but i developed… a osx daemon wich solve the issue

is just a work around but solve the problem..
need some develop into library to do this..
but i could upload the entire project of daemon.

let me know if you would like.
but i don’t have time for maintenance..

**Comment by matrivian** [comment]
Sure! I'd love to try it. Thank you so so much!

**Comment by silaic** [comment]
Tomorrow i will send you.the.c++ project with.xcode proj file and how
config the daemon.
Or would you like only the compiled daemon plus instructions?
Il giorno 17/apr/2015 01:21, "June(Jun) Guo" <notifications@github.com> ha
scritto:

**Comment by matrivian** [comment]
xcode project file and how to configure the daemon please. Thank you very much! Really appreciate your help.
