### ISSUE TITLE
failed to submit isochronous transfer x :-12

### ISSUE THREAD

**Issue by Anixxx** [OpenKinect/libfreenect#405]
hi guys, 
after I have instaled libfreenect  on windows 8.1
I get this error: 

failed to submit isochronous transfer 0 :-12
failed to submit isochronous transfer 1 :-12
failed to submit isochronous transfer 2 :-12
failed to submit isochronous transfer 3 :-12
failed to submit isochronous transfer 4 :-12
failed to submit isochronous transfer 5 :-12
failed to submit isochronous transfer 6 :-12

Thank you

**Comment by piedar** [comment]
The instructions to patch libusb for Windows have since been added to [README.md](README.md).

**Comment by LennardF1989** [comment]
@piedar Having applied the patch today, I'm getting a "Isochronous transfer error: 1". I had to resolve conflicts with Josh his patch, but did a recent change to master break more than that perhaps? Or is this a driver issue?

**Comment by piedar** [comment]
@LennardF1989 According to the [comments around that warning](https://github.com/OpenKinect/libfreenect/blob/ec0b75dd0ee6d510294335cc4cdfee9375a4bde3/src/usb_libusb10.c#L770), transfers can fail for unknown reasons and just get resubmitted in that case.  Does the stream work at all despite the warning?

**Comment by LennardF1989** [comment]
@piedar I recompiled the library and indeed noticed that even though the first try always fails, the "just try again" thing always succeeds.

However, I'm not getting any readings whatsoever. I can move it up and down, toggle the led, but anything that should produce a visual is simply black.

**Comment by LennardF1989** [comment]
Just tested the Kinect on my Xbox 360 to ensure it's not broken, it really works. I then repeated all the steps on another PC which is a Windows 10, 64-bit. Instead of an old Glut, I even used FreeGlut right now. I simply don't get any visuals.

**Comment by LennardF1989** [comment]
@JoshBlake @piedar Dove into it a little, it really seems like the iso_callback is doing something weird. The line you highlighted submits the transfer-request again, which succeeds, but upon next call to to the iso_callback, it will simply be 1 again. 

I'm suspecting Josh his patch no longer works, even though it merges fine. Kinda at loss how to solve this now... maybe anyone else on Windows can confirm it either works or doesn't for them?

**Comment by Kellen-dotdotflow** [comment]
To anyone who might run into this issue, using https://zadig.akeo.ie/ to install the drivers worked for me. Just make sure you select the libusbK drivers from the driver menu. It's kinda hard to see the little selection arrows, but they're there. It'll start out with the WinUSB driver selected, just change it to the libusbK driver and install. 

That got rid of my "failed to submit isochronous transfer 0 :-12" problem.
