### ISSUE TITLE
Missing OSX in the platform folder

### ISSUE THREAD

**Issue by granahaj** [OpenKinect/libfreenect#436]
I'm working on a MacBook Pro 2009 and have tried running this on both OS X Yosemite10.10.2  and via a partition on OS X Snow Leopard 10.6.

It seems that in the 'platforms' folder the 'osx' folder is missing. Is this repository only supported for Linux and Windows now, or am I missing something? I would really appreciate if anyone can direct me towards the necessary files to get this running with OS X. (i.e. the file 'libusb-osx-kinect.diff' which would have been in the missing OS X folder).

Thanks in advance.

**Comment by piedar** [comment]
There are no extra files for OSX.  Recent versions of libusb already include that patch.  It is recommended to install via [homebrew](http://brew.sh/):

    brew install libfreenect
