### ISSUE TITLE
Failed to open Kinect device

### ISSUE THREAD

**Issue by y5f** [OpenKinect/libfreenect#442]
I'm trying to use hornetseye_kinect gem and having error with this line : "input = KinectInput.new"
the error is as following :
/home/y5f/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hornetseye-kinect-1.1.1/lib/hornetseye-kinect/kinectinput.rb:47:in `new': Failed to open Kinect device number 0 (RuntimeError)

**Comment by piedar** [comment]
Needs more info, like output of `freenect-camtest`.  Feel free to reopen.
