### ISSUE TITLE
CMAKE_BUILD_TYPE not in use?

### ISSUE THREAD

**Issue by RanzQ** [OpenKinect/libfreenect#444]
I tried to build as Release on Windows, but cmake says:

```CMake Warning:
  Manually-specified variables were not used by the project:
    CMAKE_BUILD_TYPE```

I'm not so familiar with cmake but should I be able to build Release somehow? Debug build works.

**Comment by piedar** [comment]
If you're building with Visual Studio, you must specify the config [at build time](https://stackoverflow.com/a/24470998/1925996).  So either switch to Release config inside Visual Studio or build from command line like

    cmake --build {BUILD_DIR} --config Release

**Comment by RanzQ** [comment]
Ok, thanks. I figured it out at some point how to change it in VS.
