### ISSUE TITLE
Could not open camera

### ISSUE THREAD

**Issue by SebastianVarma** [OpenKinect/libfreenect#448]
When I ran a program that involved libfreenect, I got the following error: 
Could not open audio: -4
Failed to open motor subddevice or it is not disabled.Failed to open audio subdevice or it is not disabled.terminate called after throwing an instance of 'std::runtime_error'

**Comment by piedar** [comment]
Please try updating to dcb2929.  It should allow continuing execution if the audio device fails to load.

**Comment by piedar** [comment]
Hopefully fixed by #479 - please reopen if it still doesn't work.
