### ISSUE TITLE
Improvement: Skeleton Tracking?

### ISSUE THREAD

**Issue by ibaranov-cp** [OpenKinect/libfreenect#455]
Hello all,

Has anyone been looking into implementing the skeleton tracking feature of the Kinect 1 generation?
Any progress on that front?

**Comment by parkerlreed** [comment]
https://github.com/joaquimrocha/Skeltrack

Be sure to install GFreenect before Skeltrack https://github.com/elima/GFreenect

**Comment by piedar** [comment]
See also #556
