### ISSUE TITLE
Literally Nothing Will Compile Without Help

### ISSUE THREAD

**Issue by duffyevan** [OpenKinect/libfreenect#463]
I'm running Debian "jessie" on a raspberry pi B+ and not a single thing has compiled without me having to go into code and fixing things. I've seen other people having ridiculous problems as well. I finally got it to build everything, and now no modules will install on python and no C++ headers can be found, and some of them simply don't exist (ie. libfreekinect.h is included by libfreekinect.hpp but its nowhere on my disk). Does anyone have any idea why this disagrees so much with the raspberry pi?

**Comment by piedar** [comment]
There is no libfreekinect.h.  There are [libfreenect.h](https://github.com/OpenKinect/libfreenect/blob/master/include/libfreenect.h) and [libfreenect.hpp](https://github.com/OpenKinect/libfreenect/blob/master/wrappers/cpp/libfreenect.hpp), both of which get installed to /usr/local/include/libfreenect/ by default.

I can't offer any more advice without seeing the compiler errors.
