### ISSUE TITLE
exit not found when compiled in mac using gcc

### ISSUE THREAD

**Issue by anyong298** [OpenKinect/libfreenect#472]
Using clang, everything is OK. When I switched to gcc in mac, it complains that exit() cannot be found in wrappers/cpp/cpp_pc_viewer.cpp. 

After I added #include <cstdlib> to the file, there is no more error anymore.

**Comment by piedar** [comment]
Was it `#include <cstdlib>`?  And maybe we should use `glutLeaveMainLoop()` instead of `exit()`.
