### ISSUE TITLE
Could not open audio

### ISSUE THREAD

**Issue by Butler925** [OpenKinect/libfreenect#478]
I set up libfreenect on a Raspberry Pi 2 B with a Kinect 1473 camera and the video/depth works perfectly.  However, when I was running the demo files, a message pops up in the terminal stating "could not open audio:" followed by either -1 or -4.  I am hoping to use the Kinect camera as a microphone as well for audio commands, so this is a small problem.

I have seen a few other threads where audio errors cause the video to crash, but have not come across any solution.  Has anyone set up the 1473 camera and been able to use the microphones?

**Comment by piedar** [comment]
Hopefully fixed by #479 - please reopen if it still doesn't work.
