### ISSUE TITLE
Questions about shift2depth.

### ISSUE THREAD

**Issue by maoLB** [OpenKinect/libfreenect#481]
Nowadays i have seen some topics.It says that there are two ways for kinect device to support depth value.One way is that get depth value directly.The other way is that get raw depth from kinect using USB and then build a shift2Depth table to calculate the depth value. How can i get depth value directly?
I am new in using kinect.  Can anyone tell something about that? Thanks a lot.

**Comment by piedar** [comment]
Take a look at the [depth format enum](https://github.com/OpenKinect/libfreenect/blob/master/include/libfreenect.h#L97).  The first few formats give raw data, but `FREENECT_DEPTH_MM` converts the values to millimeters and `FREENECT_DEPTH_REGISTERED` aligns the mm values to the RGB pixel frame.
