### ISSUE TITLE
Centos 7 - No luck

### ISSUE THREAD

**Issue by mischmerz** [OpenKinect/libfreenect#496]
Built everything as explained, added udev-rules, disabled selinux but get:

bin/freenect-glview 
Kinect camera test
Number of devices found: 1
Failed to claim camera interface: LIBUSB_ERROR_NOT_FOUND
Failed to open camera subdevice or it is not disabled.Failed to open motor subddevice or it is not disabled.Failed to open audio subdevice or it is not disabled.Could not open device

#lsusb
Bus 001 Device 016: ID 045e:02ad Microsoft Corp. Xbox NUI Audio
Bus 001 Device 008: ID 045e:02b0 Microsoft Corp. Xbox NUI Motor
Bus 001 Device 017: ID 045e:02ae Microsoft Corp. Xbox NUI Camera

It *should* work .. but it doesn't. :(

**Comment by briangular** [comment]
Same exact problem here. Installed with apt to Ubuntu 16.04. Added the udev-rules from [Here](https://openkinect.org/wiki/Getting_Started#Ubuntu_Manual_Install). Restarted, and I get:

`$ freenect-glview`
`Kinect camera test`
`Number of devices found: 1`
`Failed to claim camera interface: LIBUSB_ERROR_NOT_FOUND`
`Failed to open camera subdevice or it is not disabled.Failed to open motor subddevice or it is not disabled.Failed to open audio subdevice or it is not disabled.Could not open device
`

Also, as Mischmerz, I have:

`$ lsusb | grep -i xbox`
`Bus 003 Device 020: ID 045e:02ae Microsoft Corp. Xbox NUI Camera`
`Bus 003 Device 018: ID 045e:02b0 Microsoft Corp. Xbox NUI Motor`
`Bus 003 Device 019: ID 045e:02ad Microsoft Corp. Xbox NUI Audio`

So the computer sees the USB Kinect device, but it does not work

SOOOOooooo stuck.  Can't find this error _anywhere_ else through Google. Please help.

**Comment by piedar** [comment]
Possibly fixed by #501.

**Comment by piedar** [comment]
Assumed fixed by 2ce5bd36.
