### ISSUE TITLE
Xbox 360 Kinect on Ubuntu 16.04

### ISSUE THREAD

**Issue by corus87** [OpenKinect/libfreenect#502]
Hi, I bought an Xbox 360 Kinect version 1414 and want to use the microphone array for speech recognition. Before I bought it I read a lot about the open Kinect project and after my understanding it should be simple to use the Kinect as an USB Microphone and to show up on arecord or alsamixer. 
After a lot of trying also with other solutions I found on the Internet like Kinect-audio-setup.git I managed somehow that it shows up in alsamixer, but there were no controls. 
My question is, what steps I have to do, to get only the mic array to work on Ubuntu 16.04 with a Kinect 1414? Is it even possibly that it works properly? 
After my understanding of libfreenect it should work with:

git clone https://github.com/OpenKinect/libfreenect
cd libfreenect
mkdir build
cd build
cmake .. -DBUILD_REDIST_PACKAGE=OFF
make
Or do I have to build more, or use some special firmware?

I spend the last 3 days on this and it would be nice if someone could help me to understand how to get it working.

**Comment by Yusra60445** [comment]
Hey did you finally get to connect it? I'm facing similar issue, can you help me?
