### ISSUE TITLE
Multiple kinects on python

### ISSUE THREAD

**Issue by oscarmtzz22** [OpenKinect/libfreenect#516]
How do I capture frames from multiple connected Kinects with OpenKinect on Python?
Is there a way to specify the [name|index|...] of the sensor I want to capture?

(I have already successfuly connected my 3 kinects)

Thanks.

**Comment by piedar** [comment]
The easiest way is with the synchronous interface.

```
num_devices = freenect.num_devices(ctx)

while True:
    depth_frames = [freenect.sync_get_depth(i) for i in range(num_devices)]
    video_frames = [freenect.sync_get_video(i) for i in range(num_devices)]

freenect.sync_stop()
```

To run it asynchronously, you'll need to open the devices manually and call `freenect.runloop()` from multiple threads.
