### ISSUE TITLE
Where to find Pyfreenect tutorials 

### ISSUE THREAD

**Issue by jborj006** [OpenKinect/libfreenect#577]
Hello,
Maybe I missed it but any pointers on where to find find tutorials on how to use the python libfreenect library? I haven’t been able to find anything.

**Comment by libasoles** [comment]
I don't know about blog posts, but try reading the examples. They are quite simple to understand:
https://github.com/OpenKinect/libfreenect/tree/master/wrappers/python

I'd try only cv2 demos, not the old cv ones.
