### ISSUE TITLE
Unable to clone the repository

### ISSUE THREAD

**Issue by jithendrabsy** [OpenKinect/libfreenect#583]
jithendra@kaneki:~$  git clone git://github.com/OpenKinect/libfreenect.git
Cloning into 'libfreenect'...
fatal: Unable to look up github.com (port 9418) (Name or service not known)

**Comment by libasoles** [comment]
I don't think it has to do with the repo itself. Maybe it's something in your configuration (github authentication, ports...). 

Try with the _https_ URI:

`git clone https://github.com/OpenKinect/libfreenect.git`
