### ISSUE TITLE
Cmake unable to find consistent python 3 libraries

### ISSUE THREAD

**Issue by rbiju** [OpenKinect/libfreenect#616]
When attempting to build the python wrapper, I encountered the following error. Any suggestions? I am running macOS Catalina 10.15.4

ray@Rays-MBP build % cmake .. -DBUILD_PYTHON3=ON
-- Operating system is Apple MacOS X
-- Got System Processor x86_64
-- libfreenect will be installed to /usr/local
-- Headers will be installed to /usr/local/include/libfreenect
-- Libraries will be installed to /usr/local/lib
-- Found libusb-1.0:
--  - Includes: /usr/local/include/libusb-1.0
--  - Libraries: /usr/local/lib/libusb-1.0.dylib
CMake Error at wrappers/python/CMakeLists.txt:44 (message):
  Unable to find consistent Python 3 libraries.  Python interpreter is 3.7,
  but libraries are 2.7.16.
Call Stack (most recent call first):
  wrappers/python/CMakeLists.txt:97 (Python_BUILD_EXTENSION)

-- Configuring incomplete, errors occurred!
See also "/Users/ray/Documents/Personal_Projects/Kinect_Helicopter/libfreenect/build/CMakeFiles/CMakeOutput.log".
See also "/Users/ray/Documents/Personal_Projects/Kinect_Helicopter/libfreenect/build/CMakeFiles/CMakeError.log".
ray@Rays-MBP build %

**Comment by piedar** [comment]
Hopefully fixed now with #610.
