### ISSUE TITLE
cmake error on run

### ISSUE THREAD

**Issue by nbaddorf** [OpenKinect/libfreenect#621]
I am trying to install libfreenect and when I run cmake in the Build and Fetch section of your readme, it gives me this error:

nbaddorf@Nicks-Ubuntu-Desktop-Cybertron:~/libfreenect/build$ cmake -L
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

CMake Error: The source directory "/home/nbaddorf/libfreenect/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
-- Cache values

My understanding is that it needs the CMakeLists file and I dont have it. Please help! I am a noob at CMake so I dont know what I am doing there.

**Comment by piedar** [comment]
Add `..`  to tell cmake to look in the parent directory.

```
cmake .. -L
```
