### ISSUE TITLE
Kinect

### ISSUE THREAD

**Issue by sarveshrathi** [OpenKinect/libfreenect#665]
When I use the following command
system_profiler SPUSBDataType

the output is:

2022-12-02 15:59:26.861 system_profiler[15978:2741232] SPUSBDevice: IOCreatePlugInInterfaceForService failed 0xe00002be
2022-12-02 15:59:26.871 system_profiler[15978:2741232] SPUSBDevice: IOCreatePlugInInterfaceForService failed 0xe00002be
USB:

    USB 3.0 Bus:

      Host Controller Driver: AppleUSBXHCIWPT
      PCI Device ID: 0x9cb1 
      PCI Revision ID: 0x0003 
      PCI Vendor ID: 0x8086 

        Xbox NUI Sensor:

          Product ID: 0x02c4
          Vendor ID: 0x045e  (Microsoft Corporation)
          Version: 1.00
          Serial Number: 009950565247
          Speed: Up to 5 Gb/s
          Manufacturer: Microsoft
          Location ID: 0x14400000 / 8
          Current Available (mA): 900
          Current Required (mA): 144
          Extra Operating Current (mA): 0

Thus it shows kinect sensor connected to my macbook air.

But when I run, 

freenect-glview

This is the output:

Kinect camera test
Number of devices found: 0

 I have installed libfreenect through

 brew install libfreenect

while following the following page:
https://github.com/OpenKinect/libfreenect#readme

Any Ideas what I should try? I want to connect Kinect sensor for Xbox one to my mac and want  to use it for depth sensing of hand acupoints.

**Comment by piedar** [comment]
`0x02c4` is a Kinect v2 device, so you will need to use https://github.com/OpenKinect/libfreenect2 instead.
