### ISSUE TITLE
[Feature request] Skeleon Tracking

### ISSUE THREAD

**Issue by weirdal3333** [OpenKinect/libfreenect#675]
Replicate the skeleton tracking that exists in the official Kinect SDK

**Comment by kobioneil** [comment]
Thank you

**Comment by piedar** [comment]
Sorry, such extra features are out of scope for this project.  There are various implementations found on GitHub for skeleton tracking on ROS or OpenNI2.  Seems like a "modern" approach like https://github.com/MVIG-SJTU/AlphaPose uses machine learning and a regular RGB camera.
