### ISSUE TITLE
ibfreenect fails to build after latest commit

### ISSUE THREAD

**Issue by Marwan-Refaat** [OpenKinect/libfreenect#680]
I am on Ubuntu 20.04 Cython3 (0.29.14) and Python3 (3.8.10)

When building libfreenect using:
```
cmake .. -L -DBUILD_PYTHON3=ON -DPython3_EXACTVERSION=3.8.10 -DCYTHON_EXECUTABLE=/usr/bin/cython3
```
I get the following error when generating `freenect3.c`:
```
[ 96%] Generating freenect3.c

Error compiling Cython file:
------------------------------------------------------------
...
    dev_out.ctx = ctx
    return dev_out

_depth_cb, _video_cb = None, None

cdef void depth_cb(freenect_device *dev, void *data, uint32_t timestamp) noexcept with gil:
                                                                        ^
/home/marwan/sandbox/libfreenect/wrappers/python/freenect.pyx:325:73: Syntax error in C variable declaration
```

I solved this by reverting to tag 0.7.0 and building again. 

I believe this is due to the latest commit on 2 Jan 2024 (`5341ff68aa946a11ac0df3b050f2524d7c51a825`)

**Comment by piedar** [comment]
Sorry, a9806d3 broke it even worse because `legacy_implicit_noexcept` is not necessarily defined.  With 09a1f09 it should finally be correct with a copy of the pyx file to keep cython 0.x and 3.x totally separate.
