### ISSUE TITLE
NOT AN ISSUE, THIS IS A QUESTION ( CAN'T FIND THE FORUM TO ASK THIS )

### ISSUE THREAD

**Issue by naxsisflyby** [OpenKinect/libfreenect#686]
I didn't check to code yet but wonder few things bout the software.

1. does the software support multiple kinect at the same time ?
2. Does multi kinect types ( such as gen1&2 ) work a sync for gettings better result for Mocap ?
3. round 10 ~20 kinect can used for single or multiple objects for close-mid close mocap ?
4.  last and least if someone drop the forum for those kind of q's for this repo, that's gonna be great.

Thx yall.

**Comment by piedar** [comment]
1. Yes - [see return value](https://github.com/OpenKinect/libfreenect/blob/master/examples/camtest.c#L75) of `freenect_num_devices(ctx);`
2. For gen2 device support, see [OpenKinect/libfreenect2](https://github.com/OpenKinect/libfreenect2).
3. Synchronizing the output multiple Kinects sounds like an interesting application, but out of scope for this library.
4. I don't know if there are active forums, but https://openkinect.org/ has a bunch more info about the project.

**Comment by naxsisflyby** [comment]
> 1. Yes - [see return value](https://github.com/OpenKinect/libfreenect/blob/master/examples/camtest.c#L75) of `freenect_num_devices(ctx);`
> 
>     2. For gen2 device support, see [OpenKinect/libfreenect2](https://github.com/OpenKinect/libfreenect2).
> 
>     3. Synchronizing the output multiple Kinects sounds like an interesting application, but out of scope for this library.
> 
>     4. I don't know if there are active forums, but https://openkinect.org/ has a bunch more info about the project.

Thx 4 the feedback brother, you help a lot.
