### ISSUE TITLE
Regular receipt of undersized packet.  

### ISSUE THREAD

**Issue by ros-pkg-git** [OpenKinect/libfreenect#84]
Streaming points and images I get the following.  

```
[Stream 70] Expected 1748 data bytes, but got 1908. Dropping...
[Stream 70] Expected 1748 data bytes, but got 1908. Dropping...
[Stream 70] Expected 1748 data bytes, but got 1908. Dropping...
[Stream 70] Expected 1748 data bytes, but got 1908. Dropping...
[Stream 70] Expected 1748 data bytes, but got 1908. Dropping...
[Stream 70] Expected 1748 data bytes, but got 1908. Dropping...
[Stream 70] Expected 1748 data bytes, but got 1908. Dropping...
[Stream 70] Expected 1748 data bytes, but got 1908. Dropping...
[Stream 70] Expected 1748 data bytes, but got 1908. Dropping...
```

**Comment by J-G-R** [comment]
I get the same as the original OP. I'm running libfreenect on a Beaglebone Black rev c. If I work with one stream at a time it works well - 21fps with rgb and 6-7fps with the depth stream. However if i try to work with both RGB and depth streams at the same time, I get the same error as the original OP and i receive nothing from either stream. Has any progress been made with this issue?

**Comment by piedar** [comment]
@J-G-R This is a tricky issue because I've only seen it happen briefly so I can't really say what's causing it.  Which example did you run to see the problem?

**Comment by J-G-R** [comment]
I'm running a custom application written in C. It simply gets RGB and depth frames from the kinect, compresses them and then sends them back to my laptop via TCP socket. The method i'm using can be seen below:

int kinectUpdate(void) {
	uint32_t ts;
	// Pull a (distorted) RGB frame
	int ret = freenect_sync_get_video_with_res((void **) &rgb_raw, &ts, 0,
			FREENECT_RESOLUTION_MEDIUM, FREENECT_VIDEO_RGB);
	if (ret != 0) {
		printf("Error: unable to acquire RGB stream\n");
		return ret;
	}

	// Pull a depth frame registered to the above image
	int retD = freenect_sync_get_depth_with_res((void **) &depth_registered, &ts, 0,
			FREENECT_RESOLUTION_MEDIUM, FREENECT_DEPTH_REGISTERED);

	if (retD != 0) {
		printf("Error: unable to acquire registered depth stream\n");
		return retD;
	}

	// Copy frame data to local buffers
#ifdef DOUBLEBUF
	memcpy(rgb_dbuf, rgb_raw, 640*480*3*sizeof(uint8_t));
	memcpy(depth_dbuf, depth_registered, 640*480*2*sizeof(uint8_t));
	rgb_raw = rgb_dbuf;
	depth_registered = depth_dbuf;
#endif

	return 0;
}

If I delete either of the freenect_sync methods and run it it works perfectly and I receive the frames on my laptop. I've also tried separating this method into two individual methods but that doesn't work either.

**Comment by piedar** [comment]
See if you get the same messages when running the freenect-camtest example (Ctrl-C to quit).

**Comment by J-G-R** [comment]
I ran freenect-camtest for about 5 seconds and this is the result:
freenect-camtest
[Stream 70] Negotiated packet size 1920
write_register: 0x0105 <= 0x00
write_register: 0x0006 <= 0x00
write_register: 0x0012 <= 0x03
write_register: 0x0013 <= 0x01
write_register: 0x0014 <= 0x1e
write_register: 0x0006 <= 0x02
write_register: 0x0017 <= 0x00
[Stream 80] Negotiated packet size 1920
Failed to submit isochronous transfer 0: -1
Failed to submit isochronous transfer 1: -1
Failed to submit isochronous transfer 2: -1
Failed to submit isochronous transfer 3: -1
Failed to submit isochronous transfer 4: -1
Failed to submit isochronous transfer 5: -1
Failed to submit isochronous transfer 6: -1
Failed to submit isochronous transfer 7: -1
Failed to submit isochronous transfer 8: -1
Failed to submit isochronous transfer 9: -1
Failed to submit isochronous transfer 10: -1
Failed to submit isochronous transfer 11: -1
Failed to submit isochronous transfer 12: -1
Failed to submit isochronous transfer 13: -1
Failed to submit isochronous transfer 14: -1
Failed to submit isochronous transfer 15: -1
write_register: 0x000c <= 0x00
[Stream 70] Lost 12 total packets in 0 frames (inf lppf)
write_register: 0x000d <= 0x01
write_register: 0x000e <= 0x1e
write_register: 0x0005 <= 0x01
Received depth frame at -1846614715
[Stream 70] Lost 24 total packets in 1 frames (24.000000 lppf)
write_register: 0x0047 <= 0x00
Received depth frame at -1842610405
[Stream 70] Expected max 1748 data bytes, but got 1908. Dropping...
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic 8772
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic 84b0
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Lost 12 packets
[Stream 70] Lost 36 total packets in 2 frames (18.000000 lppf)
[Stream 70] Lost too many packets, resyncing...
[Stream 70] Invalid magic 9b33
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic 1d83
[Stream 70] Invalid magic c5f8
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic 6cc9
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic f75e
[Stream 70] Invalid magic f27e
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
Received depth frame at -1838606095
Received depth frame at -1836603940
[Stream 70] Expected max 1748 data bytes, but got 1908. Dropping...
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic 83b0
[Stream 70] Invalid magic f8bf
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic c197
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic eee1
[Stream 70] Invalid magic 5ceb
[Stream 70] Invalid magic 7e4f
[Stream 70] Lost 12 packets
[Stream 70] Lost 48 total packets in 4 frames (12.000000 lppf)
[Stream 70] Lost too many packets, resyncing...
Received depth frame at -1832599630
[Stream 70] Expected max 1748 data bytes, but got 1908. Dropping...
[Stream 70] Invalid magic fffb
[Stream 70] Invalid magic 3586
[Stream 70] Invalid magic cd7f
[Stream 70] Invalid magic ffff
[Stream 70] Invalid magic 6aed
[Stream 70] Lost 6 packets
[Stream 70] Lost 54 total packets in 5 frames (10.800000 lppf)
[Stream 70] Lost too many packets, resyncing...
^CShutting down
write_register: 0x0006 <= 0x00
write_register: 0x0005 <= 0x00
Done!

**Comment by piedar** [comment]
So it's dropping packets even without doing work (other than `printf`) done in the freenect event thread.  My best guess is that the host can't keep up with all the transfers coming in.  There are a couple things you can try.

First is to compile for your particular CPU and with heavy optimizations.

    cmake .. -DCMAKE_C_FLAGS="-march=native -O3"

If that doesn't help, you can also fiddle with the `PKTS_PER_XFER` and `NUM_XFERS` constants in [usb_libusb.h](https://github.com/OpenKinect/libfreenect/blob/master/src/usb_libusb10.h#L32).  The settings for Linux are in the last block, at line 47.

Sorry I can't be of more help.  I'm 85% sure it's a hardware or USB stack issue, but it's really hard to tell.

**Comment by J-G-R** [comment]
Hmm, I'll give your suggestions a try. I'm also thinking it's a hardware issue due to the camtest failed almost instantly. I knew the RPi wasn't able to handle libfreenect so I wen't for the beaglebone which I honestly thought would be able to keep up - 1GHz processor, 512Mb RAM - but now it looks like I'll have to go for a more powerful board. I'm thinking along the lines of an odroid which has a 1.7GHz quad core processor and 2GB of RAM. Do you think that will be enough to handle libfreenect?

**Comment by piedar** [comment]
It's more an issue of USB bandwidth than CPU or RAM.  According to my rough calculation, depth and video together push roughly 20 MB/s over USB.

The ODROID is better in that regard because it has separate hosts for ethernet and USB.  The U3 should be [up to the job](https://groups.google.com/d/msg/openkinect/OoASaNLIEM4/L70DPsD1k7MJ).  But if you can spend $30 extra, go for XU3 Lite; I've seen [a report](https://groups.google.com/d/msg/openkinect/OoASaNLIEM4/7YiGltYh9uQJ) that it even works with two Kinects, one on the 2.0 port and one on the 3.0.

**Comment by J-G-R** [comment]
Thanks for the insight. I've decided to bite the bullet and go for the Odroid xu3 lite like you suggested. I'll post here if it's successful.

**Comment by J-G-R** [comment]
Update: The kinect used with libfreenect works like a dream on the odroid. I'm even receiving 30 fps on my laptop over wifi, with no dropped packets. Thanks for the advice @piedar :+1:

**Comment by Cherden** [comment]
@J-G-R is there a way to get in contact with you?
